---
title: "Assignment5"
author: "Geetika Surapaneni"
date: "1/19/2023"
output: html_document
---

2. This is Question 2: 
```{r}
my_matrix <- matrix(runif(16), nrow = 4, byrow = TRUE)
print(my_matrix)


my_logical <- runif(100) < 0.5
print(my_logical)


my_letters <- sample(letters[seq(1:26)])
print(my_letters)

my_list <- c(my_matrix, my_logical, my_letters)
print(my_list)


my_new_list <- list(my_matrix[2,2], my_logical[2], my_letters[2])
print(my_new_list)


typeof(my_new_list[[1]])

typeof(my_new_list[[2]])

typeof(my_new_list[[3]])


my_new_vector <- c(my_matrix[2,2], my_logical[2], my_letters[2])
print(my_new_vector)

typeof(my_new_vector)

```

3. This is Question 3:
```{r}

my_unis <- runif(26, min = 0, max = 10)
my_letters <- sample(LETTERS[seq(1:26)])

my_data_frame <- data.frame(my_unis, my_letters)
print(my_data_frame)

my_data_frame[,1] <- replace(x = my_data_frame[,1], list = sample(nrow(my_data_frame),4), values = NA)

which(is.na(my_data_frame))

my_data_frame[,2] <- sort(my_data_frame[,2], decreasing = FALSE)
print(my_data_frame)

mean(complete.cases(my_data_frame[,1]))

```
