---
title: "Assignment8"
author: "Geetika Surapaneni"
date: "1/26/2023"
output: html_document
---

Question 1: 

I am able to run my simulated data function from Weekly Assignment 2 with new values for the means. I have inserted the new values and ran the code below. 

Original Code: (not annotated version)
```{r}
library(tidyverse)

set.seed(1000) 

datafunction <- function(m1 = 10, sd1 = 1.5, m2 = 45, sd2 = 2){
  dFrame <- data.frame(
    Type = rep(c("Control", "Treatment"), each = 25),
    Value = c(rnorm(25, m1, sd1), rnorm(25, m2, sd2))
  )
  return(dFrame)
}

datafunction()

```

Mean Values Changed:
```{r}
set.seed(1000)

changeddata <- function(m1 = 13, sd1 = 1.9, m2 = 20, sd2 = 2){
  dFrame <- data.frame(
    Type = rep(c("Control", "Treatment"), each = 25),
    Value = c(rnorm(25, m1, sd1), rnorm(25, m2, sd2))
  )
  return(dFrame)
}

changeddata()
```
Original Code(annotated version and compared to the posted code):
```{r}
library(tidyverse)

set.seed(1000) #this function is needed to create reproducible results and can guarantee that the same random values are produced every time. this was also done in the posted code.

datafunction <- function(m1 = 10, sd1 = 1.5, m2 = 45, sd2 = 2) #the posted code include n=25, however I had put the count of each group in the line below and did not assign the sample size value to n. this makes more sense to do and would be easier to change the sample size in the future. 
  {
  dFrame <- data.frame(
    Type = rep(c("Control", "Treatment"), each = 25), #did not assign sample size to n. 
    Value = c(rnorm(25, m1, sd1), rnorm(25, m2, sd2)) 
  )
  return(dFrame)
}

data<-datafunction()
head(data) #these two lines of coding are to show only the first six values of the table. this was also done the same way in the posted code. 

anova <- aov(data[[2]] ~ data[[1]], data = data) #this is the line of coding I had found to create an anova test. 
#my default input I set as the variable I used to store the default output of my data function
#I extract the data by column instead of name.
summary(anova)

valtest <- function(d = data){
  table = summary(aov(d[[2]] ~ d[[1]], data = d))
  pvalue <- table[[1]][["Pr(>F)"]][[1]]
  return(pvalue)
}

valtest()
```





Question 2:
```{r}
## Set up libraries
library(tidyverse)
library(ggthemes)

p<- ggplot(data=dryadData, #adds the data frame needed to create plot
       aes(x=interaction(wetland, treatment),  #x variable is the 
           y=count.total.adults, fill=factor(year))) + geom_bar(position="dodge",  stat="identity", color="black") + #y variable is the total number of adults. #the fill color is by year and the color is black. 
  ylab("Number of breeding adults") +  #labels the y axis
  xlab("") + #labels the x axis, no label on this plot so the inside of the quotation marks are left blank
  scale_y_continuous(breaks = c(0,100,200,300,400,500)) + #the scale on the y axis. y axis is labeled from 0 to 500 increasing by 100.
  scale_x_discrete(labels=c("30 (Ref)", "124 (Ref)", "141 (Ref)", "25 (100m)","39 (100m)","55 (100m)","129 (100m)", "7 (30m)","19 (30m)","20 (30m)","59 (30m)")) + #the labels of each bar on the x axis
  facet_wrap(~species, nrow=2, strip.position="right") + #splits the graph into two on the same   visual
  theme_few() + scale_fill_grey() + #sets the background of the graph. the background of this graph is grey
  theme(panel.background = element_rect(fill = 'gray94', color = 'black'),  legend.position="top",  legend.title= element_blank(), axis.title.y = element_text(size=12, face= "bold", colour = "black"), strip.text.y = element_text(size = 10, face="bold", colour = "black")) +  #determines font size and color and where legend title is placed. 
  guides(fill=guide_legend(nrow=1,byrow=TRUE)) 

p
```

