---
title: "Assignment6"
author: "Geetika Surapaneni"
date: "1/23/2023"
output: html_document
---
1. 
```{r}
library(tidyverse)
data("iris")
glimpse(iris)
```
In the IRIS dataset, there are 150 observations and 5 variables. 

2. 
```{r}
iris1 <- filter(iris, Species == "virginica" | Species == "versicolor", Sepal.Length > 6, Sepal.Width > 2.5)
glimpse(iris1)  
```
In the iris1 dataset, there are 56 observations and 5 variables. 

3. 
```{r}
iris2 <- select(iris1, -(c(Petal.Length,Petal.Width)))
glimpse(iris2)  
```
In the iris2 dataset, there are 56 observations and 3 variables

4. 
```{r}
iris3 <- arrange(iris2, desc(Sepal.Length))
head(iris3)
```

5. 
```{r}
iris4 <- mutate(iris3, Sepal.Area = Sepal.Length * Sepal.Width)
glimpse(iris4)
```
In the iris2 dataset, there are 56 observations and 4 variables

6. 
```{r}
 iristab <- summarize(iris4, meanLength = mean(Sepal.Length), meanWidth = mean(Sepal.Width), TotalNumber= n())
print(iristab)
```
7. 
```{r}
iris5 <- group_by(iris4, Species)
iris5 <- summarize(iris5, meanLength = mean(Sepal.Length), meanWidth = mean(Sepal.Width), TotalNumber= n())
print(iris5)
```
8. 
```{r}
iris %>%
  filter(Species %in% c("virginica","versicolor"), Sepal.Length > 6, Sepal.Width > 2.5) %>%
  select(-(c(Petal.Length,Petal.Width))) %>%
  arrange(desc(Sepal.Length)) %>%
  mutate(Sepal.Area = Sepal.Length * Sepal.Width) %>%
  group_by(Species) %>%
  summarize(meanLength = mean(Sepal.Length), meanWidth = mean(Sepal.Width),  TotalNumber= n())
```

